# Dataset Configuration for YOLO-NAS Training
# This file defines the dataset parameters for SuperGradients

# Dataset paths
data_dir: "data"
train_images_dir: "train/images"
train_labels_dir: "train/labels"
val_images_dir: "val/images"
val_labels_dir: "val/labels"

# Class names - UPDATE THESE WITH YOUR ACTUAL CLASSES
classes:
  - "class1"  # Replace with your first class name
  - "class2"  # Replace with your second class name
  - "class3"  # Replace with your third class name
  # Add more classes as needed

# Number of classes (will be calculated automatically)
num_classes: 3  # Update this to match your number of classes

# Image settings
input_dim: [640, 640]  # Input image size for training

# Data augmentation settings
mixup: 0.0
copy_paste: 0.0
mosaic: 1.0
mosaic_prob: 1.0
mixup_prob: 1.0
mixup_alpha: 8.0
degrees: 10.0
translate: 0.1
scale: [0.1, 2.0]
shear: 2.0
perspective: 0.0
flip_ud: 0.0
flip_lr: 0.5
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4

# Additional dataset settings
cache_images: false
cache_format: "ram"
rect_training: false
